# see https://prometheus.io/docs/operating/configuration/
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
          - localhost:9093

rule_files:
  - '*-rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - localhost:9090
  - job_name: 'windows'
    scheme: https
    tls_config:
      ca_file: tls/prometheus-example-ca-crt.pem
      cert_file: tls/prometheus.example.com-client-crt.pem
      key_file: tls/prometheus.example.com-client-key.pem
    static_configs:
      - targets:
        - prometheus.example.com:9182
  - job_name: 'blackbox-http'
    scheme: https
    tls_config:
      ca_file: tls/prometheus-example-ca-crt.pem
      cert_file: tls/prometheus.example.com-client-crt.pem
      key_file: tls/prometheus.example.com-client-key.pem
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://ruilopes.com
        - https://ruilopes.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus.example.com:9115
  - job_name: 'blackbox-ssh'
    scheme: https
    tls_config:
      ca_file: tls/prometheus-example-ca-crt.pem
      cert_file: tls/prometheus.example.com-client-crt.pem
      key_file: tls/prometheus.example.com-client-key.pem
    metrics_path: /probe
    params:
      module: [ssh_banner]
    static_configs:
      - targets:
        - prometheus.example.com:22
        - ruilopes.com:22
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus.example.com:9115
