# see https://prometheus.io/docs/operating/configuration/
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

rule_files:
  - '*.rules'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - localhost:9090
  - job_name: 'windows'
    scheme: https
    tls_config:
      ca_file: tls/prometheus-example-ca-crt.pem
      cert_file: tls/prometheus.example.com-client-crt.pem
      key_file: tls/prometheus.example.com-client-key.pem
    static_configs:
      - targets:
        - prometheus.example.com:9182
